import { db } from "./db";
import { locality } from "./schema";

function id(prefix: string, index: number) {
  return `${prefix}_${String(index).padStart(4, "0")}`;
}

const bhubaneswarLocalities: string[] = [
  "Chakeisiani",
  "Acharya Vihar",
  "Jharapara",
  "Damana",
  "Jan Path",
  "Palashpalli",
  "Kapila Prasad",
  "Ashok Nagar",
  "Ghatikia",
  "Gautam Nagar",
  "Naharkanta",
  "Daruthenga",
  "Patharagadia",
  "Kalinga Vihar",
  "Jagmohan Nagar",
  "Laxmisagar",
  "Lingipur",
  "Kapileswar",
  "Andharua",
  "Subudhipur",
  "Pitapalli",
  "Hans Pal",
  "Samantarapur",
  "Ahalya Nagar",
  "Gajapati Nagar",
  "Budheswari Colony",
  "Nandan Vihar",
  "Damana Square",
  "Jayadev Vihar",
  "Atala",
  "Santoshi Vihar",
  "Vijaya Vihar",
  "Mancheswar",
  "Shastri Nagar",
  "Naharakanta Road",
  "Pandav Nagar",
  "Jadupur",
  "Sundarpada",
  "Sipasarubali",
  "Kharavela Nagar",
  "Pandra",
  "Jagannath Nagar",
  "C. V. Raman Global University",
  "Gandamunda",
  "Punjabi Colony",
  "Aiginia",
  "Rudrapur",
  "Dumuduma",
  "Rajarani Colony",
  "Chatabar",
  "Madhusudan Marg",
  "Kalpana Square",
  "Pokhariput",
  "Vani Vihar",
  "Botanda",
  "Sailashree Vihar",
  "Gottapatna",
  "Kanan Vihar",
  "Benupur",
  "Kateni",
  "IRC Village",
  "Bhouma Nagar",
  "Prasanti Vihar",
  "Bharatpur",
  "Ganesh Nagar",
  "Kendriya Vihar",
  "Nayapalli",
  "Niladri Vihar",
  "Rath Road",
  "Jagannath Vihar",
  "Unit 6",
  "Okil Bagh",
  "Palasuni",
  "Shree Vihar",
  "Mahatab Road",
  "Nakhara",
  "Bhingarpur",
  "Jatani",
  "Kausalya Ganga",
  "Jagamara",
  "Sahid Nagar",
  "Ranga Bazar",
  "Bapuji Nagar",
  "Ranasinghpur",
  "Kalinga Nagar",
  "Unit 4",
  "Kesora",
  "Maitre Vihar Road",
  "Chintamaniswar",
  "Uttampur",
  "National Highway 5",
  "Bhoi Nagar",
  "Maitri Vihar",
  "Panchasakha Nagar",
  "Sijua",
  "Saheed Nagar",
  "Mendhasala",
  "Satabdi Nagar",
  "GITA Autonomous College",
  "Phulnakhara",
  "Barampur",
  "Ghangapatna",
  "Ratnakar Bagh",
  "Garage Chaka",
  "Puri Cuttack Road",
  "Unit 8",
  "Dumduma",
  "Nuapalli",
  "Gadakana",
  "Khordha",
  "Sriram Nagar Old Town",
  "GGP Colony Rasulgarh",
  "Retang",
  "Dharma Vihar",
  "Kalarahanga",
  "Barakuda",
  "Chandrasekharpur",
  "Sisupalgarh",
  "Bainchua",
  "Gothapatna",
  "Badagada Brit Colony",
  "Balianta",
  "Jharapada",
  "Nandankanan Road",
  "Bhimatangi Housing Colony",
  "Kanan Vihar Phase 1",
  "V.S.S. Nagar",
  "Press Square",
  "Old Town",
  "Phase 2 Patia",
  "Rupali Chaka",
  "Sahaspur",
  "Rasulgarh",
  "Khandagiri",
  "Siripur",
  "Kuha",
  "KIIT Square",
  "Mausima Flyover",
  "Govt. Press Colony",
  "Malipada",
  "Chandaka",
  "Sundarpur",
  "Raghunathpur",
  "Bomikhal",
  "Gudia Pokhari",
  "Balakati",
  "Brahmeswar Patna",
  "Satya Nagar",
  "Soubhagya Nagar",
  "Jayadurga Nagar",
  "Shankarpur",
  "Badaraghunathpur",
  "Khurdha Town",
  "Baragarh Brit Colony",
  "Arugul Railway Station",
  "Patia",
  "Forest Park",
  "Nageswar Tangi",
  "Hirapur",
  "Janla",
  "Jatni",
  "Damodarpur",
  "BJB Nagar",
  "Ganga Nagar",
  "Uttara",
  "Vivekananda Marg",
  "Lewis Road",
  "Retang Mouza",
  "Satya Vihar",
  "Kalinga Stadium",
  "Siula PIPLI",
  "Dasapur",
  "Nalco Square",
  "Madanpur",
  "Kantbada",
  "Sham Pur",
  "Lakshmi Sagar",
  "Satyabhampur",
  "Tankapani Road",
  "Baramunda",
  "Pahala",
  "Surya Nagar",
  "Lumbini Vihar",
  "Arugul",
  "Paika Nagar",
  "Damdama",
  "Unit 9",
  "Patrapada",
  "Master Canteen Chowk",
  "Kateni Square",
  "Tamando",
  "Palashuni",
  "Delta Colony",
  "Patia Station Road",
  "Madhusudan Nagar",
  "Baragarh",
  "Dhauli",
  "National Highway 16",
];

const cuttackLocalities: string[] = [
  "Badambadi",
  "Buxi Bazar",
  "College Square",
  "Dolamundai",
  "Jobra",
  "Khan Nagar",
  "Madhupatna",
  "Mangalabag",
  "Nayabazar",
  "Ranihat",
  "Salepur",
  "Sikharpur",
  "Telenga Bazar",
  "Tulsipur",
  "Bidanasi",
  "CDA",
  "Markat Nagar",
  "Sambalpur Road",
  "Shitala Bazar",
  "Govind Nagar",
];

const puriLocalities: string[] = [
  "Grand Road",
  "Swargadwar",
  "Baliapanda",
  "Chakratirtha Road",
  "Sea Beach Road",
  "Mochi Sahi",
  "Dolamandap",
  "VIP Colony",
  "Penthakata",
  "Sipasarubali",
  "Brahmagiri",
  "Balighai",
  "Gop",
  "Konark Road",
  "Delanga",
];

async function main() {
  console.log("Seeding localities…");

  const rows: Array<typeof locality.$inferInsert> = [];

  bhubaneswarLocalities.forEach((name, i) => {
    rows.push({
      id: id("loc_bbsr", i + 1),
      area: "Bhubaneswar",
      name,
      lat: null,
      lng: null,
      perSqftRate: null,
    });
  });

  cuttackLocalities.forEach((name, i) => {
    rows.push({
      id: id("loc_ctc", i + 1),
      area: "Cuttack",
      name,
      lat: null,
      lng: null,
      perSqftRate: null,
    });
  });

  puriLocalities.forEach((name, i) => {
    rows.push({
      id: id("loc_puri", i + 1),
      area: "Puri",
      name,
      lat: null,
      lng: null,
      perSqftRate: null,
    });
  });

  await db.insert(locality).values(rows).onConflictDoNothing();

  console.log(`Seeded ${rows.length} localities.`);
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
