services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: zakarta-pg-dev
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zktpassword
      POSTGRES_DB: zakarta-db